blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/reill87/PromptStock/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/reill87/PromptStock#readme
    about: Read the documentation to learn more about the project
